repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      args: [--line-length=120]
-   repo: git://github.com/doublify/pre-commit-isort
    rev: v4.3.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8~=3.6.0]
